// AUTO-GENERATED by scripts/generate-item-gold.mjs — do not edit by hand.
// Source: Riot Data Dragon 16.12.1 (cdn/16.12.1/data/en_US/item.json),
// field gold.total, for every item in the live-match item pool. Re-run the generator
// after changing the pool or bumping the Data Dragon version.

// Total gold cost of each completed item, keyed by Riot item id.
export const itemGoldTotals: Record<string, number> = {
  "2065": 2200,
  "2502": 2800,
  "3003": 2900,
  "3006": 1100,
  "3020": 1100,
  "3031": 3500,
  "3036": 3300,
  "3047": 1200,
  "3053": 3200,
  "3065": 2700,
  "3068": 2700,
  "3071": 3000,
  "3075": 2450,
  "3078": 3333,
  "3084": 3000,
  "3085": 2650,
  "3089": 3500,
  "3094": 2650,
  "3107": 2300,
  "3109": 2300,
  "3111": 1250,
  "3116": 2600,
  "3135": 3000,
  "3143": 2700,
  "3157": 3250,
  "3158": 900,
  "3161": 3100,
  "3190": 2200,
  "3222": 2300,
  "3504": 2200,
  "3508": 3050,
  "3869": 400,
  "3870": 400,
  "3871": 400,
  "3876": 400,
  "4628": 2700,
  "4645": 3200,
  "6333": 3300,
  "6617": 2200,
  "6631": 3300,
  "6655": 2750,
  "6662": 2900,
  "6664": 2800,
  "6665": 3200,
  "6672": 3000,
  "6673": 3000,
  "6676": 3000,
  "6692": 2900,
  "6699": 3000,
};

// Fallback cost for an unknown id — a typical legendary price, so a missing entry
// never collapses the build pacing (used by the proportional purchase model).
export const defaultItemGold = 3000;

export function getItemGoldTotal(itemId: string): number {
  return itemGoldTotals[itemId] ?? defaultItemGold;
}
