import type { Champion } from "./championTypes";

export const championPool: Champion[] = [
  {
    id: "aatrox",
    name: "Aatrox",
    roles: ["top"],
    archetypes: ["blind-pick", "frontline", "teamfight", "carry"],
    difficulty: 74,
    metaScore: 76,
    lanePower: 78,
    teamfightPower: 82,
    scalingPower: 75,
    engagePower: 70,
    pokePower: 35,
    synergyTags: ["front-to-back", "bruiser"],
    counterTags: ["range-top", "anti-heal"],
  },
  {
    id: "ksante",
    name: "K'Sante",
    roles: ["top"],
    archetypes: ["blind-pick", "frontline", "utility"],
    difficulty: 82,
    metaScore: 80,
    lanePower: 73,
    teamfightPower: 84,
    scalingPower: 77,
    engagePower: 75,
    pokePower: 25,
    synergyTags: ["front-to-back", "peel"],
    counterTags: ["range-top", "side-lane-pressure"],
  },
  {
    id: "rumble",
    name: "Rumble",
    roles: ["top", "mid"],
    archetypes: ["lane-bully", "teamfight", "poke"],
    difficulty: 70,
    metaScore: 73,
    lanePower: 82,
    teamfightPower: 86,
    scalingPower: 68,
    engagePower: 45,
    pokePower: 76,
    synergyTags: ["wombo-combo", "magic-damage"],
    counterTags: ["long-range", "disengage"],
  },
  {
    id: "gnar",
    name: "Gnar",
    roles: ["top"],
    archetypes: ["blind-pick", "teamfight", "split-push"],
    difficulty: 76,
    metaScore: 70,
    lanePower: 76,
    teamfightPower: 80,
    scalingPower: 72,
    engagePower: 78,
    pokePower: 66,
    synergyTags: ["side-lane", "engage-window"],
    counterTags: ["hard-engage", "burst"],
  },
  {
    id: "renekton",
    name: "Renekton",
    roles: ["top"],
    archetypes: ["lane-bully", "dive", "skirmish"],
    difficulty: 60,
    metaScore: 67,
    lanePower: 86,
    teamfightPower: 67,
    scalingPower: 50,
    engagePower: 62,
    pokePower: 20,
    synergyTags: ["early-game", "dive"],
    counterTags: ["scaling-frontline", "range-top"],
  },
  {
    id: "vi",
    name: "Vi",
    roles: ["jungle"],
    archetypes: ["engage", "pick", "dive"],
    difficulty: 58,
    metaScore: 75,
    lanePower: 42,
    teamfightPower: 76,
    scalingPower: 61,
    engagePower: 88,
    pokePower: 12,
    synergyTags: ["lockdown", "dive"],
    counterTags: ["disengage", "cleanse"],
  },
  {
    id: "sejuani",
    name: "Sejuani",
    roles: ["jungle"],
    archetypes: ["frontline", "engage", "utility"],
    difficulty: 56,
    metaScore: 72,
    lanePower: 38,
    teamfightPower: 82,
    scalingPower: 74,
    engagePower: 84,
    pokePower: 22,
    synergyTags: ["melee-synergy", "front-to-back"],
    counterTags: ["anti-tank", "poke"],
  },
  {
    id: "lee-sin",
    name: "Lee Sin",
    roles: ["jungle"],
    archetypes: ["skirmish", "dive", "pick"],
    difficulty: 88,
    metaScore: 69,
    lanePower: 35,
    teamfightPower: 70,
    scalingPower: 55,
    engagePower: 78,
    pokePower: 18,
    synergyTags: ["early-game", "playmaking"],
    counterTags: ["scaling-jungle", "point-click-cc"],
  },
  {
    id: "maokai",
    name: "Maokai",
    roles: ["jungle", "support"],
    archetypes: ["frontline", "engage", "utility"],
    difficulty: 52,
    metaScore: 74,
    lanePower: 40,
    teamfightPower: 83,
    scalingPower: 76,
    engagePower: 80,
    pokePower: 48,
    synergyTags: ["vision-control", "front-to-back"],
    counterTags: ["anti-tank", "high-dps"],
  },
  {
    id: "nidalee",
    name: "Nidalee",
    roles: ["jungle"],
    archetypes: ["poke", "skirmish", "carry"],
    difficulty: 86,
    metaScore: 65,
    lanePower: 28,
    teamfightPower: 58,
    scalingPower: 66,
    engagePower: 25,
    pokePower: 88,
    synergyTags: ["early-game", "poke"],
    counterTags: ["hard-engage", "frontline"],
  },
  {
    id: "azir",
    name: "Azir",
    roles: ["mid"],
    archetypes: ["scaling", "teamfight", "carry"],
    difficulty: 90,
    metaScore: 79,
    lanePower: 75,
    teamfightPower: 88,
    scalingPower: 92,
    engagePower: 62,
    pokePower: 72,
    synergyTags: ["front-to-back", "late-game"],
    counterTags: ["dive", "long-range-pick"],
  },
  {
    id: "orianna",
    name: "Orianna",
    roles: ["mid"],
    archetypes: ["teamfight", "utility", "scaling"],
    difficulty: 74,
    metaScore: 78,
    lanePower: 72,
    teamfightPower: 90,
    scalingPower: 84,
    engagePower: 65,
    pokePower: 70,
    synergyTags: ["ball-delivery", "front-to-back"],
    counterTags: ["assassin", "long-range"],
  },
  {
    id: "ahri",
    name: "Ahri",
    roles: ["mid"],
    archetypes: ["pick", "skirmish", "utility"],
    difficulty: 68,
    metaScore: 74,
    lanePower: 74,
    teamfightPower: 72,
    scalingPower: 68,
    engagePower: 67,
    pokePower: 64,
    synergyTags: ["pick", "roam"],
    counterTags: ["frontline", "cleanse"],
  },
  {
    id: "taliyah",
    name: "Taliyah",
    roles: ["mid", "jungle"],
    archetypes: ["global", "pick", "utility"],
    difficulty: 78,
    metaScore: 72,
    lanePower: 73,
    teamfightPower: 76,
    scalingPower: 75,
    engagePower: 58,
    pokePower: 76,
    synergyTags: ["map-control", "pick"],
    counterTags: ["hard-dive", "burst"],
  },
  {
    id: "corki",
    name: "Corki",
    roles: ["mid"],
    archetypes: ["poke", "scaling", "carry"],
    difficulty: 64,
    metaScore: 71,
    lanePower: 68,
    teamfightPower: 77,
    scalingPower: 86,
    engagePower: 28,
    pokePower: 90,
    synergyTags: ["poke", "late-game"],
    counterTags: ["hard-engage", "dive"],
  },
  {
    id: "jinx",
    name: "Jinx",
    roles: ["bot"],
    archetypes: ["scaling", "teamfight", "carry"],
    difficulty: 62,
    metaScore: 78,
    lanePower: 68,
    teamfightPower: 90,
    scalingPower: 92,
    engagePower: 20,
    pokePower: 54,
    synergyTags: ["front-to-back", "reset"],
    counterTags: ["dive", "assassin"],
  },
  {
    id: "zeri",
    name: "Zeri",
    roles: ["bot"],
    archetypes: ["scaling", "carry", "skirmish"],
    difficulty: 84,
    metaScore: 72,
    lanePower: 62,
    teamfightPower: 88,
    scalingPower: 90,
    engagePower: 26,
    pokePower: 55,
    synergyTags: ["enchanter", "late-game"],
    counterTags: ["point-click-cc", "hard-engage"],
  },
  {
    id: "kalista",
    name: "Kalista",
    roles: ["bot"],
    archetypes: ["lane-bully", "skirmish", "engage"],
    difficulty: 82,
    metaScore: 70,
    lanePower: 86,
    teamfightPower: 70,
    scalingPower: 58,
    engagePower: 64,
    pokePower: 50,
    synergyTags: ["early-game", "support-engage"],
    counterTags: ["range-scaling", "point-click-cc"],
  },
  {
    id: "xayah",
    name: "Xayah",
    roles: ["bot"],
    archetypes: ["teamfight", "carry", "utility"],
    difficulty: 70,
    metaScore: 74,
    lanePower: 72,
    teamfightPower: 84,
    scalingPower: 80,
    engagePower: 35,
    pokePower: 58,
    synergyTags: ["self-peel", "rakan"],
    counterTags: ["long-range", "poke"],
  },
  {
    id: "varus",
    name: "Varus",
    roles: ["bot"],
    archetypes: ["poke", "lane-bully", "utility"],
    difficulty: 68,
    metaScore: 75,
    lanePower: 80,
    teamfightPower: 74,
    scalingPower: 70,
    engagePower: 55,
    pokePower: 86,
    synergyTags: ["poke", "pick"],
    counterTags: ["hard-engage", "dive"],
  },
  {
    id: "rakan",
    name: "Rakan",
    roles: ["support"],
    archetypes: ["engage", "utility", "skirmish"],
    difficulty: 74,
    metaScore: 77,
    lanePower: 70,
    teamfightPower: 86,
    scalingPower: 72,
    engagePower: 90,
    pokePower: 20,
    synergyTags: ["xayah", "dive", "teamfight"],
    counterTags: ["point-click-cc", "disengage"],
  },
  {
    id: "nautilus",
    name: "Nautilus",
    roles: ["support"],
    archetypes: ["engage", "frontline", "pick"],
    difficulty: 50,
    metaScore: 73,
    lanePower: 78,
    teamfightPower: 80,
    scalingPower: 60,
    engagePower: 88,
    pokePower: 18,
    synergyTags: ["pick", "dive"],
    counterTags: ["disengage", "poke"],
  },
  {
    id: "rell",
    name: "Rell",
    roles: ["support", "jungle"],
    archetypes: ["engage", "frontline", "teamfight"],
    difficulty: 66,
    metaScore: 72,
    lanePower: 68,
    teamfightPower: 88,
    scalingPower: 68,
    engagePower: 92,
    pokePower: 10,
    synergyTags: ["wombo-combo", "frontline"],
    counterTags: ["disengage", "poke"],
  },
  {
    id: "alistar",
    name: "Alistar",
    roles: ["support"],
    archetypes: ["engage", "frontline", "utility"],
    difficulty: 58,
    metaScore: 68,
    lanePower: 66,
    teamfightPower: 82,
    scalingPower: 70,
    engagePower: 86,
    pokePower: 8,
    synergyTags: ["dive", "peel"],
    counterTags: ["enchanter", "poke"],
  },
  {
    id: "lulu",
    name: "Lulu",
    roles: ["support"],
    archetypes: ["enchanter", "utility", "scaling"],
    difficulty: 54,
    metaScore: 69,
    lanePower: 65,
    teamfightPower: 78,
    scalingPower: 82,
    engagePower: 15,
    pokePower: 54,
    synergyTags: ["hyper-carry", "peel"],
    counterTags: ["hard-engage", "pick"],
  },
];
